title: Register Dynamics
description: |
  Register Dynamics works with companies and governments to apply their data usefully,
  responsibly and ethically. Our expertise ranges from tiny telemetry systems with
  one or two stakeholders up to database clusters with thousands of nodes used by
  several business units.
url: https://www.register-dynamics.co.uk
logo: "images/logo-2.png"

plugins:
- jekyll-seo-tag

collections:
  projects:
    output: no
  posts:
    output: yes
    permalink: /blog/:title
  data-trusts:
    output: yes
  authors:
    output: yes

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: blog
  - scope:
      path: ""
      type: authors
    values:
      layout: author
  - scope:
      path: ""
      type: data-trusts
    values:
      permalink: /data-trusts/:title:output_ext
      layout: report-article
      date: 2019-04-14 00:00:00
      image: images/logo-2.png
      seo:
        type: Report
      authors:
        - Andy Bennett
        - Simon Worthington

order:
- personal-data-exchange
- open-registers
- wwi-archive
- payroll-analytics
- knodium
- geniedb

twitter:
  username: RegDyn
  card: summary_large_image

data:
  authors:
    Andy Bennett:
      twitter: databasescaling
    Simon Worthington:
      twitter: 51M0NW
