title: Register Dynamics

collections:
  projects:
    output: no
  posts:
    output: yes

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: blog

order:
- personal-data-exchange
- open-registers
- wwi-archive
- payroll-analytics
- knodium
- geniedb

authors:
  - name: Andy Bennett
    twitter: databasescaling
  - name: Simon Worthington
    twitter: 51M0NW
