title: Register Dynamics
description: |
  Register Dynamics is a team of data strategists and technologists supporting government to embed best practises in data.
  We develop new technology, frameworks and operational models to support the better use of data both in the public and private sectors.
baseurl: ""
url: https://www.register-dynamics.co.uk
email: hello@register-dynamics.co.uk
logo: "images/logo-2.png"

plugins:
- jekyll-seo-tag
- jekyll-feed
- jekyll-sitemap
- jekyll-liquify

sass:
  style: compressed

collections:
  projects:
    output: yes
    permalink: /case-studies/:title
  posts:
    output: yes
    permalink: /blog/:title
  data-trusts:
    output: yes
  publications:
    output: no
  authors:
    output: yes
  services:
    output: yes
  specialisms:
    output: yes
  jobs:
    output: yes

defaults:
  - values:
      image: "images/logo-slide.png"
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      date: 2016-02-24 00:00:00
  - scope:
      path: ""
      type: posts
    values:
      layout: blog
  - scope:
      path: ""
      type: authors
    values:
      layout: author
  - scope:
      path: ""
      type: data-trusts
    values:
      permalink: /data-trusts/:title:output_ext
      layout: report-article
      date: 2019-04-14 00:00:00
      image: "images/logo-2.png"
      seo:
        type: Report
      authors:
        - Andy Bennett
        - Simon Worthington
  - scope:
      path: ""
      type: jobs
    values:
      seo:
        type: JobPosting
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: services
    values:
      layout: page
  - scope:
      path: ""
      type: specialisms
    values:
      layout: page

twitter:
  username: RegDyn
  card: summary_large_image
