---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
  config:
    date_format: MMM YYYY
    time_format: 
    export_format: YYYY-MM-DD
- type: file
  name: image
  label: image
- type: text
  name: client
  label: client
- type: textarea
  name: excerpt
  label: excerpt
pages:
- _projects/making-trade-policy-into-operational-data.md
- _projects/spreadsheet-standards.md
- _projects/transforming-uk-prisons.md
